### ISSUE TITLE
What is the benchmark performance

### ISSUE THREAD

**Issue by tapanjo92** [pwasystem/zip#1]
Hi,

Can it zip 20GB on browser without using much of memory or CPU

Thank You

**Comment by pwasystem** [comment]
Hi,
I haven't tested it.
However, compressing 20Gb is an arduous task for any processor.
This script I set up to generate simple files, just to clone my framework to generate PWA applications.
I believe it will depend on hardware capabilities and script runtime limitations in each browser.

If you test, be sure to let me know.

Note, the script just merges the files, i didn't apply any compression algorithms.

Best regardsSpider

**Comment by pwasystem** [comment]
> Hi,
> 
> Can it zip 20GB on browser without using much of memory or CPU
> 
> Thank You

I ran a test.

The maximum file size I was able to upload without crashing the browser was 99Mb.
Above that the browser has an error, I believe it is because of the storage space limit existing in browsers or the script execution limit.

hugs
Spider
