### ISSUE TITLE
Doesn't work; modTime in makeZip is a function

### ISSUE THREAD

**Issue by garyo** [pwasystem/zip#2]
In `makeZip` it includes `modTime` in a few places. But that is a function, so it ends up including the text of the function body, not an actual mod time.

**Comment by pwasystem** [comment]
Hello thank you so much.  I'll check the code as soon as I have a few minutes.  If you are urgent, there is a 100% working copy in the "clone" script of my WebpoW system.  You can also try changing the value in the script and check the results, then send me the correction.

**Comment by garyo** [comment]
I didn't need mod times anyway, so I just stubbed all that out. Just thought you should know.

**Comment by pgibe** [comment]
I dare to add that now that the `modTime()` function problem has been fixed, remains the problem of the value of `zip[name].modTime`, which is set to the value of `files[i].lastModifiedDate`. lastModifiedDate is a deprecated property (see [here](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate)), and `files[i].lastModified` should be used instead.

**Comment by pwasystem** [comment]
Thanks!

I made the suggested change.
